const phrases = [
    "Baby/Kid",
    "Tazer",
    "S.W.A.T",
    "Alleged Terrorist",
    "Car Chase",
    "Speaking Spanish",
    "Innocent Injured",
    "Police Dismissed",
    "Drone / Robot / Helicopter",
    "Magazine Change",
    "Survives Shooting",
    "Balistic Sheild",
    "Police Gunfire",
    "Less Lethal",
    "Suspect Gunfire",
    "EMS Called",
    "Offered Water",
    "Heavy Gunfire",
    "Mayor Apology",
    "Negotiations",
    "Screaming Wife / Mom / Woman",
    "Pit Maneuever",
    "Innocent Animal",
    "Domestic Violence",
    "K9",
    "Bike",
    "Shooting From Police car",
    "Knife",
    "Gunfire Under 20 Sec",
    "Request Backup",
    "Drunk Dad",
    "Under The Influence",
    "Fake Gun",
    "'Show Your Hands'",
    "'Dude / Boss'",
    "Crossfire",
    "Wearing Wifebeater",
    "Tire Screech",
    "Knee On The Back"
  ];